name: Build and Push Docker Image

on:
  push:
    branches: [dev, main]

jobs:
  deploy:
    name: build and push on docker registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build docker image (Dev)
        if: github.ref == 'refs/heads/dev'
        env:
          DOCKER_IMAGE_TAGNAME: dev
        run: make build

      - name: Build docker image (Production)
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE_TAGNAME: latest
        run: make build

      - name: Tag image name to push on registery
        run: make tag-remote

      - name: Push to Docker Registery
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: make push
